name: Security

on:
  pull_request:
    branches:
      - main

jobs:
  pinact:
    name: Run pinact
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run pinact
        uses: suzuki-shunsuke/pinact-action@3d49c6412901042473ffa78becddab1aea46bbea # v1.3.1
        with:
          skip_push: true

  ghalint:
    name: Run ghalint
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install ghalint
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          mise_toml: |
            [tools]
            ghalint = "1.5.5"

      - name: Run ghalint
        run: |
          ghalint run
          ghalint run-action

  actionlint:
    name: Run actionlint
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Install actionlint
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          mise_toml: |
            [tools]
            actionlint = "1.7.10"

      - name: Run actionlint
        run: |
          actionlint

  safe-chain:
    name: Scan with safe-chain
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - name: Run safe-chain
        shell: bash
        run: |
          curl -fsSL https://raw.githubusercontent.com/AikidoSec/safe-chain/main/install-scripts/install-safe-chain.sh | sh -s -- --ci
